# Offline beat map for the music tracks: python3 tools/beatmap.py > src/audio/beatmap.js
# Needs librosa (pip install librosa). Re-run whenever a track in src/audio/music is added or replaced.
#
# Each track becomes { t0, d } where t0 is the first beat (seconds) and d holds 3 chars per beat: the gap to the
# next beat in centiseconds (2 base-36 chars) and the beat's strength 0-9 (kick onset x section loudness), so quiet
# intros and breakdowns pulse softly and drops hit harder.
import glob, json, os, sys
import librosa
import numpy as np

SR = 22050
HOP = 512
out = {}
for path in sorted(glob.glob(os.path.join(os.path.dirname(__file__), '..', 'src', 'audio', 'music', '*.mp3'))):
    name = os.path.splitext(os.path.basename(path))[0]
    y, sr = librosa.load(path, sr=SR, mono=True)
    # Low-band onset envelope (kick/bass) drives the strength; the full-band one tracks the beat grid.
    S = np.abs(librosa.stft(y, hop_length=HOP))
    freqs = librosa.fft_frequencies(sr=sr)
    low = librosa.onset.onset_strength(S=librosa.amplitude_to_db(S[freqs < 180]), sr=sr, hop_length=HOP)
    full = librosa.onset.onset_strength(y=y, sr=sr, hop_length=HOP)
    _, frames = librosa.beat.beat_track(onset_envelope=full, sr=sr, hop_length=HOP)
    rms = librosa.feature.rms(S=S, hop_length=HOP)[0]
    # Section loudness: ~4 s moving average, scaled so the loud parts of the track sit near 1.
    k = int(4 * sr / HOP)
    loud = np.convolve(rms, np.ones(k) / k, mode='same')
    loud = np.clip(loud / np.percentile(loud, 90), 0, 1)
    kick = np.array([low[max(0, f - 2):f + 3].max() for f in frames])
    kick = np.clip(kick / max(1e-6, np.percentile(kick, 90)), 0, 1)
    strength = np.clip(0.35 + 0.65 * kick, 0, 1) * loud[frames] ** 1.5
    times = librosa.frames_to_time(frames, sr=sr, hop_length=HOP)
    d = []
    for i, t in enumerate(times):
        gap = round((times[i + 1] - t) * 100) if i + 1 < len(times) else 0
        gap = min(gap, 36 * 36 - 1)
        d.append(np.base_repr(gap, 36).lower().rjust(2, '0') + str(int(round(strength[i] * 9))))
    out[name] = {'t0': round(float(times[0]), 3), 'd': ''.join(d)}
    print(name, len(times), file=sys.stderr)

print('// Generated by tools/beatmap.py: beat times and strengths per music track (see that script for the format).')
print('export const BEATMAP = {')
for name, v in out.items():
    print(f"  {json.dumps(name)}: {{ t0: {v['t0']}, d: '{v['d']}' }},")
print('};')
